#!/usr/bin/env python3
"""Build the release-facing audit matrix for the 48 book illustration slots.

The two print manifests prove that each book has a checksum-bound review
derivative.  This matrix makes the remaining human and production gates
visible in one place without promoting a concept to final art.
"""

from __future__ import annotations

import csv
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CSV_OUT = ROOT / "design" / "plate-selection-audit.csv"
MD_OUT = ROOT / "design" / "plate-selection-audit.md"


def rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as stream:
        return list(csv.DictReader(stream))


def main() -> None:
    plate_rows = {row["plate_id"]: row for row in rows(ROOT / "design/plate-manifest.csv")}
    audit: list[dict[str, str]] = []
    for work in ("Iliad", "Odyssey"):
        slug = work.lower()
        selections = {int(row["book"]): row for row in rows(ROOT / f"design/{slug}-plate-selection.csv")}
        manifest = json.loads((ROOT / f"assets/print/illustrations/{slug}/manifest.json").read_text(encoding="utf-8"))
        records = {int(row["book"]): row for row in manifest["plates"]}
        for book in range(1, 25):
            selection = selections[book]
            record = records[book]
            plate = plate_rows[selection["plate_id"]]
            source = ROOT / record["source"]
            derivative = ROOT / record["print"]
            audit.append({
                "volume": work,
                "book": str(book),
                "placeholder_slot": f"{'ILI' if work == 'Iliad' else 'ODY'}-{book:02d}",
                "plate_id": selection["plate_id"],
                "passage": record["passage"],
                "selection_status": selection["selection_status"],
                "approval_status": selection["approval_status"],
                "source_type": plate["source_type"],
                "creator": plate["creator"],
                "rights_status": plate["rights_status"],
                "source_asset": record["source"],
                "source_exists": str(source.is_file()).lower(),
                "print_derivative": record["print"],
                "derivative_exists": str(derivative.is_file()).lower(),
                "derivative_spec": f"{record['printPixels'][0]}x{record['printPixels'][1]} px; {record['printPpi']} PPI; {record['embeddedProfile']}",
                "art_direction_gate": "pending",
                "caption_range_gate": "pending",
                "rights_credit_gate": "pending",
                "native_master_gate": "pending",
                "physical_proof_gate": "pending",
                "notes": selection["notes"],
            })

    fields = list(audit[0])
    with CSV_OUT.open("w", newline="", encoding="utf-8") as stream:
        writer = csv.DictWriter(stream, fieldnames=fields, lineterminator="\n")
        writer.writeheader()
        writer.writerows(audit)

    by_volume = {work: [row for row in audit if row["volume"] == work] for work in ("Iliad", "Odyssey")}
    lines = [
        "# Plate-selection audit",
        "",
        "This matrix is the release-control view of the forty-eight illustration",
        "slots. It binds each placeholder to exactly one current print-review",
        "candidate while keeping art direction, caption/range, rights/credit,",
        "native-master, and physical-proof gates explicitly open as separate fields.",
        "",
        "## Current evidence",
        "",
        "- 48 of 48 book slots have exactly one ordered selection record.",
        "- 48 of 48 selections are marked `provisional-print-review` and `pending`.",
        "- 48 of 48 candidates are original `CastaliaInstitute` work; historical",
        "  Blake/Flaxman/Piroli material is tracked separately in the source manifest.",
        "- 48 of 48 checksum-bound derivatives exist at 2055 × 3142 px, 300 PPI,",
        "  embedded sRGB; this is review geometry, not final printer approval.",
        "",
        "## Release holds",
        "",
        "No row may be changed to approved until an editor locks the exact Greek/English",
        "range and caption, an art director approves the image, rights and creator",
        "credit are signed, the native master is archived, and a physical proof has",
        "passed inspection. These five decisions are separate CSV fields so one green",
        "decision cannot obscure another open hold.",
        "",
        "| Volume | Slots | Current state |",
        "|---|---:|---|",
    ]
    for work, volume_rows in by_volume.items():
        lines.append(f"| {work} | {len(volume_rows)} | 24 provisional selections; all approvals pending |")
    lines.extend([
        "",
        f"Source of truth: [`plate-selection-audit.csv`](plate-selection-audit.csv). Generated by `scripts/build_plate_selection_audit.py`.",
        "",
    ])
    MD_OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {CSV_OUT} and {MD_OUT} ({len(audit)} slots)")


if __name__ == "__main__":
    main()
